SELECT * FROM MEAL;
ALTER TABLE MEAL
ADD CONSTRAINT UNIQUE(NAME);

ALTER TABLE
MODIFY NAME VARCHAR(255) NOT NULL;



SELECT * FROM INGREDIENT;
ALTER TABLE INGREDIENT
MODIFY PRICE DOUBLE NOT NULL;

ALTER TABLE INGREDIENT
MODIFY NAME VARCHAR(255) NOT NULL;

ALTER TABLE INGREDIENT
MODIFY IS_GLUTEN_FREE BOOLEAN NOT NULL;