  CREATE TABLE  CHEAP_MEALS AS
  SELECT * FROM MEAL
  WHERE PRICE < 15;

  CREATE TABLE VEGAN_INGREDIENT AS
  SELECT * FROM INGREDIENT WHERE FALSE;

 INSERT INTO VEGAN_INGREDIENT
 SELECT * FROM INGREDIENT WHERE VEGAN

 CREATE VIEW EXPENSIVE_MEAL AS
 SELCET * FROM MEAL WHERE PRICE > 14

 CREATE VIEW LACTOSE_FREE_INGREDIENT AS
 SELECT * FROM INGREDIENT WHERE !CONTAINS_LACTOSE;

 CREATE TABLE HIGH_CALORIE_MEAL AS
  SELECT * FROM MEAL WHERE CALORIES > 650;