SELECT NAME FROM INGREDIENT

SELECT *
FROM INGREDIENT ORDER BY NAME

SELECT *
FROM INGREDIENT ORDER BY GLUTEN_FREE DESC

SELECT * FROM MEAL
WHERE PRICE<15.0

SELECT * FROM INGREDIENT
WHERE VEGETARIAN

SELECT * FROM MEAL
WHERE CALORIES > 500

SELECT * FROM MEAL
WHERE PRICE>= 15 && PRICE <=16

SELECT * FROM INGREDIENT
WHERE CONTAINS_LACTOSE && GLUTEN_FREE

SELECT * FROM MEAL
WHERE PRICE <15 || CALORIES > 600

SELECT * FROM INGREDIENT
WHERE VEGAN || GLUTEN_FREE

SELECT * FROM MEAL
WHERE NAME = 'RISOTTO'

SELECT * FROM INGREDIENT
WHERE !CONTAINS_LACTOSE

SELECT * FROM MEAL
WHERE PRICE > 20 && CALORIES < 800