SELECT *, MAX(PRICE) FROM MEAL
WHERE CALORIES >500

SELECT *, AVG(CALORIES) FROM MEAL
WHERE PRICE > 15

SELECT *, MAX(PRICE) AS MAX_PRICE FROM MEAL
HAVING MAX_PRICE > 10

SELECT * , AVG(PRICE)  AS CIAO FROM MEAL
HAVING PRICE < CIAO

SELECT * , AVG(PRICE)  AS CIAO FROM MEAL
HAVING PRICE < CIAO && CALORIES >600