LOWER ( RENDE TUTTO IN LOWER CASE)
UPPER ( RENDE TUTTO IN UPPER CASE)
TRIM  (RIMUOVE GLI SPAZI INIZIALI E FINALI)
LENGHT (RITORNA LA LUNGHEZZA DELLA STRINGA IN BYTES)
SUBSTRING ( PERMETTE DI 'STAMPARE' DOPO UN DETERMINATO NUMERO DI CARATTERI O CONDIZIONI)
ROUND(RESTITUISCE UN VALORE NUMERICO ARROTONDATO)
DATE_ADD ( AGGIUNGE ALLA DATA UN VALORE SPECIFICO E SELEZIONATO)
DATE_SUB (SOTTRAE ALLA DATA UN VALORE SPECIFICO E SELEZIONATO)
FORMAT (PERMETTE DI DARE UN FORMATO ALLA STRINGA (COME UNA CONCATENAZIONE))






SELECT DATE_ADD(DATE_ADD(NOW(), INTERVAL 17 DAY), INTERVAL 8 MONTH) AS BIRTHDAY_DATE
SELECT DATE_FORMAT(DATE_ADD(NOW(),17,8), '00:00:00') AS MIDNIGHT;